winget install -e --id 7zip.7zip
winget install -e --id Adobe.Acrobat.Reader.64-bit
winget install -e --id Audacity.Audacity
winget install -e --id BlueJTeam.BlueJ
winget install -e --id DBBrowserForSQLite.DBBrowserForSQLite
winget install -e --id alexx2000.DoubleCommander
winget install -e --id JGraph.Draw
winget install -e --id Mozilla.Firefox
winget install -e --id Foxit.FoxitReader
winget install -e --id Freeplane.Freeplane
winget install -e --id GeoGebra.Classic
winget install -e --id GIMP.GIMP
winget install -e --id Git.Git
winget install -e --id Google.Chrome
winget install -e --id GreenfootTeam.Greenfoot
winget install -e --id HandBrake.HandBrake
winget install -e --id JetBrains.IntelliJIDEA.Community
winget install -e --id IrfanSkiljan.IrfanView
winget install -e --id BellSoft.LibericaJDK.8.Full
winget install -e --id BellSoft.LibericaJDK.17.Full
winget install -e --id KDE.Kdenlive
winget install -e --id KeePassXCTeam.KeePassXC
winget install -e --id KDE.Krita
winget install -e --id TheDocumentFoundation.LibreOffice
winget install -e --id logisim-evolution.logisim-evolution
winget install -e --id MarkText.MarkText
winget install -e --id Musescore.Musescore
winget install -e --id Notepad++.Notepad++
winget install -e --id OBSProject.OBSStudio
winget install -e --id Obsidian.Obsidian
winget install -e --id OpenShot.OpenShot
winget install -e --id syvaidya.openstego
winget install -e --id JohnMacFarlane.Pandoc
winget install -e --id AngusJohnson.PDFTKBuilder
winget install -e --id Python.Python.3.10
winget install -e --id Gluon.SceneBuilder
winget install -e --id MITMediaLab.Scratch.3
winget install -e --id SumatraPDF.SumatraPDF
winget install -e --id TexasInstruments.TI-Nspire.CXStudent
winget install -e --id IDRIX.VeraCrypt
winget install -e --id avosskuehler.viana
winget install -e --id Microsoft.VisualStudioCode
winget install -e --id VideoLAN.VLC
winget install -e --id XnSoft.XnView.Classic
winget install -e --id XnSoft.XnViewMP